---
# load vault vars
# (promene z vault.yml budou dostupne automaticky, kdyz je soubor v group_vars
# balicky co chceme na kazdem serveru
common_packages:
  - curl
  - vim
  - htop

# casova zona
timezone_name: Europe/Prague

web_server: nginx
nginx_listen_port: 80
nginx_server_name: "_"
